apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-steward-1-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-steward-1-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: partner-partner-steward-1-auth-job
      namespace: partner-ns
    network:
      name: baf
      kubernetes_url: https://7B34BE9F7FCCDCFBD55C5A043C8D936D.yl4.ap-south-1.eks.amazonaws.com
    image:
      name: partner
      repository: alpine:3.9.4
    vault:
      address: http://aaa20205874044d9eb4ce1b69352648a-441162845.ap-south-1.elb.amazonaws.com:8200
      keyPath: partner.stewards
      identity: partner-steward-1
      admin_auth_path: kubernetes-partner-admin-auth
      policy: partner-partner-steward-1-ro
      policy_content: path \"/partner/stewards/partner-steward-1/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-partner-partner-steward-1-auth
    account:
      admin_service: partner-admin-vault-auth
      admin_role: rw
      service: partner-partner-steward-1-vault-auth
      role: ro
