apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: provider-provider-endorser-transaction
      namespace: provider-ns
    network:
      name: baf
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: provider
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://a6850d0335da240939edd35945d6d551-1933730648.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: provider-admin-vault-auth
      auth_path: kubernetes-provider-admin-auth
    organization:
      name: provider
      adminIdentity:
        name: authority-trustee
        did: 9Dc28VbXHRTGHS8bQ9SYNX
        path: authority/trustees
      newIdentity:
        name: provider-endorser
        role: ENDORSER
        did: 6hBZfNj2jQgstwC3ZtRfh5
        verkey: 46xi47pd16zgcfjCMR9X5ng4UnL2kiXF248sbTGdJ25R
        path: provider/endorsers
    node:
      name: provider
