apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: partner-partner-endorser
      namespace: partner-ns
    network:
      name: baf
    image:
      name: partner
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://aaa20205874044d9eb4ce1b69352648a-441162845.ap-south-1.elb.amazonaws.com:8200
      keyPath: partner.endorsers
      identity: partner-endorser
      auth_path: kubernetes-partner-admin-auth
    account:
      service: partner-admin-vault-auth
      role: rw
