apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: provider-provider-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: provider-provider-endorser
      namespace: provider-ns
    network:
      name: baf
    image:
      name: provider
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://ad2ef6c6065c640129296516a9d2bc03-1686572389.ap-south-1.elb.amazonaws.com:8200
      keyPath: provider.endorsers
      identity: provider-endorser
      auth_path: kubernetes-provider-admin-auth
    account:
      service: provider-admin-vault-auth
      role: rw
