apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-baf-ac-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-baf-ac-auth-job
  chart:
    path: hyperledger-indy/charts/indy-auth-job
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: authority-baf-ac-auth-job
      namespace: authority-ns
    network:
      name: baf
      kubernetes_url: https://7B34BE9F7FCCDCFBD55C5A043C8D936D.yl4.ap-south-1.eks.amazonaws.com
    image:
      name: authority
      repository: alpine:3.9.4
    vault:
      address: http://aaa20205874044d9eb4ce1b69352648a-441162845.ap-south-1.elb.amazonaws.com:8200
      keyPath: authority.baf-ac
      identity: baf-ac
      admin_auth_path: kubernetes-authority-admin-auth
      policy: authority-baf-ac-ro
      policy_content: path \"/authority/+/+/+/public*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-authority-baf-ac-auth
    account:
      admin_service: authority-admin-vault-auth
      admin_role: rw
      service: authority-baf-ac-vault-auth
      role: ro
