apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-endorser-acme
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-endorser-acme
  chart:
    path: examples/identity-app/charts/acme
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      namespace: partner-ns
      name: partner-endorser
    organization:
      name: partner
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: partner-endorser
        repository: index.docker.io/sownak/aries-agents:1.11.0
    service:
      ports: 
        service: 15033
        endpoint: 15034
      
      address: partner-endorser.indy.entrustient.net
      
      ledger: http://authority-webserver.indy.entrustient.net:15010
      genesis: http://authority-webserver.indy.entrustient.net:15010/genesis
    vault:
      address: http://ad2ef6c6065c640129296516a9d2bc03-1686572389.ap-south-1.elb.amazonaws.com:8200
      serviceAccountName: partner-partner-endorser-vault-auth
      authPath: kubernetes-partner-partner-endorser-auth
      endorserName: partner-endorser
      role: ro
    storage:
      size: 128Mi
      className: partner-aws-baremetal-storageclass
    proxy:
      
      provider: "ambassador"
