apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-webserver
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-webserver
  chart:
    path: examples/identity-app/charts/webserver
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      namespace: authority-ns
      name: authority-webserver
    organization:
      name: authority
    image:
      pullSecret: regcred
      init:
        name: authority-webserver-init
        repository: alpine:3.9.4
      server:
        name: authority-webserver
        repository: index.docker.io/sownak/von-network-base:1.11.0
    service:
      port: 8000
    vault:
      address: http://ad2ef6c6065c640129296516a9d2bc03-1686572389.ap-south-1.elb.amazonaws.com:8200
      serviceAccountName: authority-authority-trustee-vault-auth
      authPath: kubernetes-authority-authority-trustee-auth
      trusteeName: authority-trustee
      role: ro
    storage:
      size: 128Mi
      className: authority-aws-baremetal-storageclass
    proxy:
      
      provider: "ambassador"
      external_url: authority-webserver.indy.entrustient.net
      port: 15010
