apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"7rZ8mUYG8dRcocTuHyxRJv","role":"0","verkey":"4jgU52UtFhCEX8KgJz3Lwfp6XPrccEHjVk92eTRskvy7"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"7wRfdh498izEVmdxTD1jSm","role":"0","verkey":"4nLTUAASCYpvWkU9Bbn1jQWq49RpVCN1QBWTaveCMA9H"},"metadata":{"from":"7rZ8mUYG8dRcocTuHyxRJv"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"L9LePguBNwV5oRZi8utuKd","role":"2","verkey":"BSAzj3B1jz2eMsV1BzjSZDN3fiTfFxDUDM1C6nE39Aky"},"metadata":{"from":"7wRfdh498izEVmdxTD1jSm"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"38ysnGHzZTSRX298aGTATh","role":"2","verkey":"2AaGkaS9oJWFjYpesSU2eY92x8WofEMbp2gjXysNdGrQ"},"metadata":{"from":"7wRfdh498izEVmdxTD1jSm"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"7z9BeJikpncoqBgDjsoMfB","role":"0","verkey":"4opJuTtxYQEgJgnAHvXkGWUrKYoQSmF9rg5Fnjhktvr4"},"metadata":{"from":"7rZ8mUYG8dRcocTuHyxRJv"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"6p13hS9pLSrxpudzEDe2CN","role":"2","verkey":"4AgG4e6Ru8ucoW17zNBGCKvpzhysPXpDFKEAWSFufidG"},"metadata":{"from":"7z9BeJikpncoqBgDjsoMfB"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"NzM26bKsEXdgo46ySqhFHS","role":"2","verkey":"Cz7B82Cf1pZkC1Ge7Z7Ztg7aK8G9mCywooAxpikPcga4"},"metadata":{"from":"7z9BeJikpncoqBgDjsoMfB"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
