apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: ssh://git@github.com/sauveer/indy-deployer.git
    ref: develop
  values:
    metadata:
      name: partner-partner-endorser-transaction
      namespace: partner-ns
    network:
      name: baf
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: partner
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://ad2ef6c6065c640129296516a9d2bc03-1686572389.ap-south-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: partner-admin-vault-auth
      auth_path: kubernetes-partner-admin-auth
    organization:
      name: partner
      adminIdentity:
        name: authority-trustee
        did: WJt4qFvAANWtAuDPYv7LXe
        path: authority/trustees
      newIdentity:
        name: partner-endorser
        role: ENDORSER
        did: Wzc5LXVk97kzvipaRwquY9
        verkey: HM9LSZECWNpmFaWjq8t54FkTV9JLa6k3v2j2K6WFePBX
        path: partner/endorsers
    node:
      name: partner
